<?xml version="1.0"?>
<robot name="cube" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find world_model_data)/data/models/xacro/common.xacro"/>

  <xacro:macro name="cube" params="name length width height
                                   color *origin">

    <link name="${name}-base">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${height/2.}"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${height/2.}"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0 0.0 ${height/2.}"/>
      <mass value="0.3"/>
      <inertia ixx="0.1" ixy="0.01" ixz="0.01" iyy="0.1" iyz="0.01" izz="0.1"/>
    </inertial>
    </link>

    <gazebo reference="${name}-base">
      <material>Gazebo/${color}</material>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <mu1>1.1</mu1>
      <mu2>1.1</mu2>
      <minDepth>0.001</minDepth>
      <!-- <selfCollide>true</selfCollide> -->
      <!-- <maxVel>0</maxVel> -->
      <!-- <dampingFactor>2</dampingFactor> -->
    </gazebo>
    
  </xacro:macro>

  <xacro:arg name="name" default="o1"/>
  <xacro:arg name="length" default="0.053"/>
  <xacro:arg name="width" default="0.053"/>
  <xacro:arg name="height" default="0.053"/>
  <xacro:arg name="color" default="Red"/>
  <xacro:arg name="xyz" default="0 0 0"/>
  <xacro:arg name="rpy" default="0 0 0"/>
  
  <xacro:cube name="$(arg name)"
              length="$(arg length)" width="$(arg width)"
              height="$(arg height)" color="$(arg color)">
      <origin xyz="$(arg xyz)" rpy="$(arg rpy)" />    
  </xacro:cube>
  
</robot>
