<?xml version="1.0"?>
<robot name="work_area" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find world_model_data)/data/models/xacro/common.xacro"/>

  <xacro:macro name="work_area" params="name parent length width depth *origin">

    <link name="${name}-base">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${depth/2.}"/>
      <geometry>
        <box size="${length} ${width} ${depth}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
    </link>

    <link name="${name}-bottom">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.005"/>
      </geometry>
      <material name="test">
        <color rgba="0.63 0.32 0.18 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>

    <joint name="joint_${name}_base" type="fixed">
      <xacro:insert_block name="origin" /> <!-- transform from base link to this joint frame -->  
      <parent link="${parent}"/>
      <child link="${name}-base" />
    </joint>

    <joint name="joint_${name}_bottom" type="fixed">
      <xacro:insert_block name="origin" /> <!-- transform from base link to this joint frame -->  
      <parent link="${parent}"/>
      <child link="${name}-bottom" />
    </joint>

  </xacro:macro>

</robot>
