<?xml version="1.0"?>
<robot name="block" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find world_model_data)/data/models/xacro/common.xacro"/>

  <xacro:macro name="cube" params="name parent length width height *origin">

    <link name="${name}-base">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${height/2.}"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="color1">
        <color rgba="0.7 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${height/2.}"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.0 0.0 ${height/2.}"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>

    <joint name="joint_${name}_base" type="fixed">
      <xacro:insert_block name="origin" /> <!-- transform from base link to this joint frame -->  
      <parent link="${parent}"/>
      <child link="${name}-base" />
    </joint>

  </xacro:macro>

</robot>
