<?xml version="1.0"?>
<robot params="name parent width depth height *origin">
 xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find world_model_data)/data/models/xacro/common.xacro"/>

  <xacro:macro name="refrigerator" params="name parent width depth height *origin">

    <link name="${name}-base">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${height/2.}"/>
      <geometry>
        <box size="${depth} ${width} ${height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
    </link>

    <link name="${name}-bottom">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} 0.005"/>
      </geometry>
      <material name="test">
        <color rgba="0.63 0.32 0.18 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} 0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>

    <link name="${name}-up">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} 0.005"/>
      </geometry>
      <material name="test">
        <color rgba="0.63 0.32 0.18 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${width} 0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>


    <link name="${name}-left">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${height} 0.005"/>
      </geometry>
      <material name="test">
        <color rgba="0.63 0.32 0.18 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${height} 0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>

    <link name="${name}-right">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${height} 0.005"/>
      </geometry>
      <material name="test">
        <color rgba="0.63 0.32 0.18 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${depth} ${height} 0.005"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.01" ixz="0.01" iyy="1.0" iyz="0.01" izz="1.0"/>
    </inertial>
    </link>





    <joint name="joint_${name}_base" type="fixed">
      <xacro:insert_block name="origin" /> <!-- transform from base link to this joint frame -->  
      <parent link="${parent}"/>
      <child link="${name}-base" />
    </joint>

    <joint name="joint_${name}_bottom" type="fixed">
      <xacro:insert_block name="origin" /> <!-- transform from base link to this joint frame -->  
      <parent link="${parent}"/>
      <child link="${name}-bottom" />
    </joint>

    <joint name="joint_${name}_up" type="fixed">
      <parent link="${name}-base"/>
      <child link="${name}-up"/>
      <origin xyz="0 0 ${height}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_${name}_left" type="fixed">
      <parent link="${name}-base"/>
      <child link="${name}-left" />
      <origin xyz="0 ${width/2.} ${height/2.}" rpy="1.57 0 0"/>
    </joint>

    <joint name="joint_${name}_right" type="fixed">
      <parent link="${name}-base"/>
      <child link="${name}-right"/>
      <origin xyz="0 -${width/2.} ${height/2.}" rpy="1.57 0 0"/>
    </joint>

  </xacro:macro>

</robot>
